# Generated by Django 5.2.4 on 2025-08-02 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm_app.category",
            ),
            preserve_default=False,
        ),
    ]
